# Generated by Django 4.1.5 on 2023-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_friends_options_alter_users_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="users",
            name="password2",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
