name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check if requirements.txt is empty
      run: |
        if [ ! -s chitChatBackend/requirements.txt ]; then
          echo "Skipping installation as requirements.txt is empty."
          exit 0
        fi
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r chitChatBackend/requirements.txt
    - name: Change Directory
      run: cd chitChatBackend
    - name: Run Tests
      run: |
        python manage.py test
