name: React Convention Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check package.json
        run: |
          if [ ! -f "chitfront/package.json" ]; then
            echo "Error: 'package.json' file not found"
            exit 1
          fi

      - name: Install dependencies
        run: |
          cd chitfront
          npm ci

      - name: Install @testing-library/jest-dom
        run: |
          cd chitfront
          npm install --save-dev @testing-library/jest-dom@^5.14.1

      - name: Run tests
        run: |
          cd chitfront
          npm test
